name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build
        run: ./gradlew build

      - name: Setup environment
        run: |
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^minecraft_version >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/gradle.properties | grep ^mod_version >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WoodCutter${{ env.mod_version }}+mc${{ env.minecraft_version }}
          path: build/libs/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: WoodCutter v${{ env.mod_version }} for Minecraft v${{ env.minecraft_version }}
          tag_name: ${{ env.mod_version }}
          name: ${{ env.mod_version }}+mc${{ env.minecraft_version }}
          target_commitish: ${{ github.sha }}
          files: |
            **/build/libs/woodcutter-*.jar